name: CI with Sentinel Integration

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Run tests
        run: |
          python -m pytest test_*.py -v
        continue-on-error: true
      
      - name: Notify Sentinel on failure
        if: failure()
        run: |
          curl -X POST ${{ secrets.SENTINEL_URL }}/webhooks/ci/failure \
            -H "Content-Type: application/json" \
            -d '{"repo": "${{ github.repository }}", "failing_test": "pytest", "logs": "Test failure detected", "diff": "CI failure"}'
        continue-on-error: true

  notify-sentinel:
    needs: test
    if: failure()
    runs-on: ubuntu-latest
    steps:
      - name: Notify Sentinel of CI failure
        uses: actions/github-script@v7
        with:
          script: |
            const payload = {
              repo: process.env.GITHUB_REPOSITORY,
              failing_test: 'tests/',
              logs: 'CI failure detected',
              diff: 'Automated CI failure notification'
            };
            
            // Use the ngrok URL from secrets
            const sentinelUrl = process.env.SENTINEL_URL + '/webhooks/ci/failure';
            
            try {
              const response = await fetch(sentinelUrl, {
                method: 'POST',
                headers: { 'Content-Type': 'application/json' },
                body: JSON.stringify(payload)
              });
              console.log(`Sentinel notification sent: ${response.status}`);
            } catch (error) {
              console.log('Sentinel notification failed:', error.message);
            }
        env:
          SENTINEL_URL: ${{ secrets.SENTINEL_URL }}
